9) Blog App/app/routes/user_routes.py
from flask import Blueprint, flash, render_template, request, redirect, url_for
from app.forms.form_models import AddUserForm, UpdateUserForm
from app.services.user_service import *
from app.utils.auth_guard import login_required
from app.utils.encryption import *

user_routes = Blueprint('user_routes', __name__)


@user_routes.route('/user/list')
@login_required([1]) #only for admin access
def list():
    users = get_users()
    return render_template('user/list.html', users=users)


@user_routes.route('/user/add', methods=['GET', 'POST'])
@login_required([1]) #only for admin access
def add():
    form = AddUserForm()
    
    if request.method == 'POST':
        if form.validate_on_submit():
            name = form.name.data
            email = form.email.data
            password = form.password.data

            existing_user = get_user_by_email(email)
            if existing_user:
                flash("Email is already registered.", "danger")
                return render_template('user/add.html', form=form)

            add_user(name, email, password)
            flash("User created successfully.", "success")
            return redirect(url_for('user_routes.add'))
    
    return render_template('user/add.html', form=form)


@user_routes.route('/user/update/<string:id>', methods=['GET', 'POST'])
@login_required([1])
def update(id):
    form = UpdateUserForm()
    user = get_user_by_id(decrypt_id(id))

    if not user:
        return "User not found", 404

    if request.method == 'POST':
        if form.validate_on_submit():
            name = form.name.data.strip()
            email = form.email.data.strip()

            existing_user = get_user_by_email(email, user['id'])
            if existing_user:
                flash("Email is already registered.", "danger")
                return redirect(url_for('user_routes.update', id=id))

            update_user(user['id'], name, email)
            flash("User updated successfully.", "success")
            return redirect(url_for('user_routes.list')) 
    else:
        form.name.data = user['name']
        form.email.data = user['email']

    return render_template('user/update.html', form=form, id=id)


@user_routes.route('/user/delete/<string:id>')
@login_required([1]) #only for admin access
def delete(id):
    delete_user(decrypt_id(id))
    flash("user deleted successfully.", "success")
    return redirect(url_for('user_routes.list'))

9) Blog App/app/templates/user/add.html
{% extends 'base.html' %}

{% block title %}Add User{% endblock %}

{% block content %}
<section class="py-3 py-md-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
                <div class="card border border-light-subtle rounded-3 shadow-sm">
                    <div class="card-body">
                        <div class="text-center mb-3">
                            <h2>Add User</h2>
                        </div>
                        
                        <form action="/user/add" method="POST">
                            {{ form.hidden_tag() }}

                            <div class="row gy-2 overflow-hidden px-3">

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Name" value="{{ form.name.data or '' }}">
                                        <label for="name" class="form-label">Name <small class="text-danger">*</small></label>
                                        {% if form.name.errors %}
                                            <small class="text-danger">{{ form.name.errors[0] }}</small>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="email" name="email" id="email" class="form-control" placeholder="Email" value="{{ form.email.data or '' }}">
                                        <label for="email" class="form-label">Email <small class="text-danger">*</small></label>
                                        {% if form.email.errors %}
                                            <small class="text-danger">{{ form.email.errors[0] }}</small>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="text" name="password" id="password" class="form-control" placeholder="Password" value="{{ form.password.data or '' }}">
                                        <label for="password" class="form-label">Password <small class="text-danger">*</small></label>
                                        {% if form.password.errors %}
                                            <small class="text-danger">{{ form.password.errors[0] }}</small>
                                        {% endif %}
                                    </div>
                                </div>
                                
                                
                                <div class="col-12">
                                    <div class="d-grid my-3">
                                        <button class="btn btn-primary btn-lg" type="submit">Add</button>
                                    </div>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

9) Blog App/app/templates/user/list.html
{% extends 'base.html' %}

{% block title %}User List{% endblock %}

{% block content %}
<section class="py-3">
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card border border-light-subtle rounded-3 shadow-sm">
                    <div class="card-body">
                        <div class="text-center text-decoration-underline">
                            <a href="{{ url_for('user_routes.add') }}" 
                            class="btn btn-sm btn-primary float-end" title="Add New User">Add</a>
                            <h2>User List</h2>
                        </div>

                        <div class="row mt-3">

                            <table class="table table-bordered" id="userTable">
                                <thead class="table-primary">
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th class="text-center">Total Blogs</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for user in users %}
                                    <tr>
                                        <td>{{ user.name }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="text-center">{{ user.blog_count }}</td>
                                        <td class="text-center">
                                            <a href="{{ url_for('user_routes.update', id=encrypt_id(user.id) ) }}" class="btn btn-success btn-sm">Edit</a>
                                            <a href="{{ url_for('user_routes.delete', id=encrypt_id(user.id) ) }}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $('#userTable').DataTable();
    $('#userNav').addClass('active')

</script>
{% endblock %}

9) Blog App/app/templates/user/update.html
{% extends 'base.html' %}

{% block title %}Update User{% endblock %}

{% block content %}
<section class="py-3 py-md-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
                <div class="card border border-light-subtle rounded-3 shadow-sm">
                    <div class="card-body">
                        <div class="text-center mb-3">
                            <h2>Update User</h2>
                        </div>
                        
                        <form action="/user/update/{{id}}" method="POST">
                            {{ form.hidden_tag() }}

                            <div class="row gy-2 overflow-hidden px-3">

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Name" value="{{ form.name.data or '' }}">
                                        <label for="name" class="form-label">Name <small class="text-danger">*</small></label>
                                        {% if form.name.errors %}
                                            <small class="text-danger">{{ form.name.errors[0] }}</small>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="email" name="email" id="email" class="form-control" placeholder="Email" value="{{ form.email.data or '' }}">
                                        <label for="email" class="form-label">Email <small class="text-danger">*</small></label>
                                        {% if form.email.errors %}
                                            <small class="text-danger">{{ form.email.errors[0] }}</small>
                                        {% endif %}
                                    </div>
                                </div>

                                
                                <div class="col-12">
                                    <div class="d-grid my-3">
                                        <button class="btn btn-primary btn-lg" type="submit">Update</button>
                                    </div>
                                </div>

                                <div class="col-12 text-center">
                                    <a href="{{ url_for('user_routes.list') }}">Back to list</a>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}