9) Blog App/app/routes/auth_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from flask_bcrypt import Bcrypt

from app.forms.form_models import ResetPasswordForm, SignupForm, UpdateUserForm
from app.services.user_service import *
from app.utils.auth_guard import *
from app.utils.encryption import *
from app.utils.mail_sender import send_reset_email

bcrypt = Bcrypt()
auth_routes = Blueprint('auth_routes', __name__)


@auth_routes.route('/')
def index():
    return redirect(url_for('auth_routes.login'))


@auth_routes.route('/login', methods=['GET', 'POST'])
@login_not_required()
def login():

    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        
        user = get_user_by_email(email)

        if user and bcrypt.check_password_hash(user['password'], password):
            session['user_id'] = user['id']
            session['user_name'] = user['name']
            session['user_role'] = user['role']
            session['user_profile'] = user['profile_path']
            session.permanent = True

            return redirect(url_for('home_routes.home'))
        else:
            flash('Invalid email or password.', 'danger')

    return render_template('auth/login.html')


@auth_routes.route('/forgot-password', methods=['GET', 'POST'])
@login_not_required()
def forgot_password():
    if request.method == 'POST':
        email = request.form['email']
        if not email.strip():
            flash("Email is required.", "danger")
            return redirect(url_for('auth_routes.forgot_password')) 
        
        user = get_user_by_email(email)

        if not user:
            flash("Email does not belongs to us.", "danger")
            return redirect(url_for('auth_routes.forgot_password'))

        reset_url = f"{request.url_root}reset-password/{encrypt_id(user['id'])}"

        if send_reset_email(email, user['name'], reset_url):
            flash("Reset link sent to your email.", "success")
        else:
            flash("Failed to send email. Try again later.", "danger")

        return redirect(url_for('auth_routes.forgot_password'))

    return render_template('auth/forgot.html')


@auth_routes.route('/reset-password/<string:id>', methods=['GET', 'POST'])
@login_not_required()
def reset_password(id):
    form = ResetPasswordForm()
    user = get_user_by_id(decrypt_id(id))

    if not user:
        flash("Invalid reset link or user not found.", "danger")
        return redirect(url_for('auth_routes.login'))

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        update_user_password(decrypt_id(id), hashed_password)
        flash("Password updated successfully. You can now log in.", "success")
        return redirect(url_for('auth_routes.login'))

    return render_template('auth/reset.html', form=form, id=id)


@auth_routes.route('/signup', methods=['GET', 'POST'])
@login_not_required()
def signup():
    form = SignupForm()
    
    if request.method == 'POST':
        if form.validate_on_submit():
            name = form.name.data
            email = form.email.data
            password = form.password.data

            existing_user = get_user_by_email(email)
            if existing_user:
                flash("Email is already registered.", "danger")
                return render_template('auth/signup.html', form=form)

            add_user(name, email, password)
            flash("Signup successful! You can now log in.", "success")

            return redirect(url_for('auth_routes.login'))
    
    return render_template('auth/signup.html', form=form)


@auth_routes.route('/update-profile', methods=['GET', 'POST'])
@login_required() #for all users
def profile():
    form = UpdateUserForm()
    user_id = session['user_id']
    user = get_user_by_id(user_id)

    if not user:
        return "User not found", 404

    if request.method == 'POST':
        if form.validate_on_submit():
            name = form.name.data.strip()
            email = form.email.data.strip()

            existing_user = get_user_by_email(email, user_id)
            if existing_user:
                flash("Email is already registered.", "danger")
                return redirect(url_for('auth_routes.profile'))

            update_user(user_id, name, email)

            updated_user = get_user_by_id(user_id)
            session['user_name'] = updated_user['name']
            session['user_email'] = updated_user['email']

            flash("Profile updated successfully.", "success")
            return redirect(url_for('auth_routes.profile'))
    else:
        form.name.data = user['name']
        form.email.data = user['email']

    return render_template('auth/update-profile.html', form=form)

@auth_routes.route('/update_password', methods=['GET', 'POST'])
@login_required() #for all users
def update_password():
    form = ResetPasswordForm()
    user_id = session['user_id']
    user = get_user_by_id(user_id)

    if not user:
        return "User not found", 404

    if form.validate_on_submit():
        old_password = request.form['old_password']
        if not bcrypt.check_password_hash(user['password'], old_password.strip()):
            flash("Old password not matched.", "danger")
            return redirect(url_for('auth_routes.update_password'))
        
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        update_user_password(user_id, hashed_password)
        flash("Password updated successfully.", "success")
        return redirect(url_for('auth_routes.update_password'))

    return render_template('auth/update-password.html', form=form)


@auth_routes.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth_routes.login'))

9) Blog App/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Blog App{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        .alert-custom{
            position: absolute; width: 420px; top:70px; right: 10px; z-index: 5;
        }
    </style>
</head>
<body class="bg-light m-1">

    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            {% if session.get('user_id') %}
                <a class="navbar-brand" href="{{ url_for('home_routes.home') }}">Home</a>
                <div class="collapse navbar-collapse justify-content-between">
                    <ul class="navbar-nav">
                        {% if session.get('user_role') == 1 %}
                            <li class="nav-item">
                                <a class="nav-link" id="userNav" href="{{ url_for('user_routes.list') }}">Users</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" id="blogNav" href="{{ url_for('blog_routes.list') }}">Blogs</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="{{ session.get('user_profile') or url_for('static', filename='uploads/default_profile.png') }}"
                                    alt="Profile" class="rounded-circle me-2" width="30" height="30">
                                {{ session.get('user_name') }}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
                                <li><a class="dropdown-item" href="{{ url_for('auth_routes.profile') }}"> 👤 Update Profile</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('auth_routes.update_password') }}"> 🔒 Update Password</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item text-danger" href="{{ url_for('auth_routes.logout') }}"> 🔓 Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            {% else %}
                <a class="navbar-brand" href="{{ url_for('auth_routes.login') }}">Blog System</a>

            {% endif %}

        </div>
    </nav>
    
    

    <div class="row m-1">
        
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div id="msgAlert"
                class="alert alert-{{ category }} alert-custom alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $('#msgAlert').delay(5000).fadeOut('slow');
    </script>
</body>
</html>