9) Blog App/app/routes/blog_routes.py
from flask import Blueprint, flash, render_template, request, redirect, session, url_for
from app.forms.form_models import BlogForm
from app.services.blog_service import *
from app.utils.auth_guard import login_required
from app.utils.encryption import *

blog_routes = Blueprint('blog_routes', __name__)


@blog_routes.route('/blog/list')
@login_required()
def list():
    blogs = get_blogs(session['user_id'] if session['user_role'] == 2 else None)
    return render_template('blog/list.html', blogs=blogs)


@blog_routes.route('/blog/detail/<string:id>')
@login_required()
def detail(id):
    blog = get_blog_by_id(decrypt_id(id))
    if not blog:
        return "Blog not found", 404

    return render_template('blog/detail.html', blog=blog)


@blog_routes.route('/blog/add', methods=['GET', 'POST'])
@login_required([2])
def add():
    form = BlogForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user_id = session['user_id']
            title = form.title.data
            content = form.content.data
            image_file = form.image.data

            add_blog(user_id, title, content, image_file)
            flash("Blog added successfully.", "success")
            return redirect(url_for('blog_routes.list'))
    
    return render_template('blog/add.html', form=form)


@blog_routes.route('/blog/update/<string:id>', methods=['GET', 'POST'])
@login_required([2])
def update(id):
    form = BlogForm()
    blog = get_blog_by_id(decrypt_id(id))

    if not blog:
        return "blog not found", 404

    if request.method == 'POST':
        if form.validate_on_submit():
            title = form.title.data
            content = form.content.data
            image_file = form.image.data

            update_blog(blog['id'], title, content, image_file, blog['image_path'])
            flash("Blog updated successfully.", "success")
            return redirect(url_for('blog_routes.list')) 

    return render_template('blog/update.html', form=form, blog=blog)


@blog_routes.route('/blog/delete/<string:id>')
@login_required()
def delete(id):
    delete_blog(decrypt_id(id))
    flash("Blog deleted successfully.", "success")
    return redirect(url_for('blog_routes.list'))

9) Blog App/app/templates/blog/add.html
{% extends 'base.html' %}

{% block title %}Add Blog{% endblock %}

{% block content %}
<section class="py-3 py-md-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
                <div class="card border border-light-subtle rounded-3 shadow-sm">
                    <div class="card-body">
                        <div class="text-center mb-3">
                            <h2>Add New Blog</h2>
                        </div>
                        
                        <form action="/blog/add" method="POST" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}

                            <div class="row gy-2 overflow-hidden px-3">

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="text" name="title" id="title" placeholder="Title" value="{{ form.title.data or '' }}" class="form-control">
                                        <label for="title" class="form-label">Title <small class="text-danger">*</small></label>
                                        {% if form.title.errors %}
                                            <div class="text-danger">{{ form.title.errors[0] }}</div>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <textarea name="content" id="content" placeholder="Content" class="form-control">{{ form.content.data or '' }}</textarea>
                                        <label for="content" class="form-label">Content <small class="text-danger">*</small></label>
                                        {% if form.content.errors %}
                                            <div class="text-danger">{{ form.content.errors[0] }}</div>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="file" name="image" id="image" class="form-control">
                                        <label for="image" class="form-label">Upload Image</label>
                                        {% if form.image.errors %}
                                            <div class="text-danger">{{ form.image.errors[0] }}</div>
                                        {% endif %}
                                    </div>
                                </div>

                                
                                <div class="col-12">
                                    <div class="d-grid my-3">
                                        <button class="btn btn-primary btn-lg" type="submit">Add</button>
                                    </div>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

9) Blog App/app/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ blog.title }}{% endblock %}

{% block content %}
<section class="py-3">
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card border border-light-subtle rounded-3 shadow-sm">
                    <div class="card-body">

                        <div class="row">
                            <div class="col-md-8 mx-auto text-center">
                                <h1 class="my-1 text-decoration-underline">{{ blog.title }}</h1>
                                <div class="my-3 d-flex justify-content-between">
                                    <div>
                                        <b>Author: </b> {{ blog.author }}
                                    </div>
                                    <div><b>Published: </b> {{ blog.created_at }}</div></div>
                                {% if blog.image_path %}
                                    <img src="{{ '/' + blog.image_path }}" class="img-fluid rounded mb-4" alt="Blog Image" style="width: 500px; height: 300px;">
                                {% else %}
                                    <img src="{{url_for('static', filename='uploads/defualt-blog.png')}}" class="img-fluid rounded mb-4" alt="Default Blog Image" style="width: 500px; height: 300px;">
                                {% endif %}
                    
                                <div class="mb-4">
                                    <p class="lead">{{ blog.content }}</p>
                                </div>
                    
                                <hr>
                    
                                <a href="{{ url_for('blog_routes.list') }}">Back to Blogs</a>
                                <br>
                                <br>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

9) Blog App/app/templates/blog/list.html
{% extends 'base.html' %}

{% block title %}Blogs{% endblock %}

{% block content %}
<section class="py-3">
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card border border-light-subtle rounded-3 shadow-sm">
                    <div class="card-body">
                        {% if session.get('user_role') == 2 %}
                            <div class="text-center text-decoration-underline">
                                <a href="{{ url_for('blog_routes.add') }}" 
                                class="btn btn-sm btn-primary float-end" title="Add New User">Add Blog</a>
                                <h2>Blog List</h2>
                            </div>
                        {% endif %}

                        <div class="row mt-3">

                            <table class="table table-bordered" id="blogTable">
                                <thead class="table-primary">
                                    <tr>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for blog in blogs %}
                                    <tr>
                                        <td>{{ blog.title  }}</td>
                                        <td>
                                            {% if session.get('user_id') == blog.user_id %}
                                                <b class="text-info">You</b>
                                            {% else %}
                                                {{ blog.auther }}
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            <a href="{{ url_for('blog_routes.detail', id=encrypt_id(blog.id) ) }}" class="btn btn-primary btn-sm">View</a>
                                            
                                            {% if session.get('user_role') == 2 %}
                                                <a href="{{ url_for('blog_routes.update', id=encrypt_id(blog.id) ) }}" class="btn btn-success btn-sm">Edit</a>
                                            {% endif %}

                                            <a href="{{ url_for('blog_routes.delete', id=encrypt_id(blog.id) ) }}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $('#blogTable').DataTable();
    $('#blogNav').addClass('active')
</script>
{% endblock %}

9) Blog App/app/templates/blog/update.html
{% extends 'base.html' %}

{% block title %}Update Blog{% endblock %}

{% block content %}
<section class="py-3 py-md-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
                <div class="card border border-light-subtle rounded-3 shadow-sm">
                    <div class="card-body">
                        <div class="text-center mb-3">
                            <h2>Update Blog</h2>
                        </div>
                        
                        <form action="/blog/update/{{encrypt_id(blog['id'])}}" method="POST" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}

                            <div class="row gy-2 overflow-hidden px-3">

                                {% if blog.image_path %}
                                    <div class="col-12 text-center mb-3">
                                        <img src="{{ '/' + blog.image_path }}" alt="Blob Image" class="rounded-circle me-2" width="80" height="80">
                                    </div>
                                {% endif %}

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="text" name="title" id="title" placeholder="Title" value="{{ blog['title'] }}" class="form-control">
                                        <label for="title" class="form-label">Title <small class="text-danger">*</small></label>
                                        {% if form.title.errors %}
                                            <div class="text-danger">{{ form.title.errors[0] }}</div>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <textarea name="content" id="content" placeholder="Content" class="form-control">{{ blog['content'] }}</textarea>
                                        <label for="content" class="form-label">Content <small class="text-danger">*</small></label>
                                        {% if form.content.errors %}
                                            <div class="text-danger">{{ form.content.errors[0] }}</div>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating mb-3">
                                        <input type="file" name="image" id="image" class="form-control">
                                        <label for="image" class="form-label">Upload Image</label>
                                        {% if form.image.errors %}
                                            <div class="text-danger">{{ form.image.errors[0] }}</div>
                                        {% endif %}
                                    </div>
                                </div>

                                
                                <div class="col-12">
                                    <div class="d-grid my-3">
                                        <button class="btn btn-primary btn-lg" type="submit">Update</button>
                                    </div>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}